repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    'types_or': [c++, c]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.12
  hooks:
    - id: insert-license
      name: "Insert license header in C++ source files"
      args: [--license-filepath=docs/legal_header.txt,
             '--comment-style=/*| *| */',
             --detect-license-in-X-top-lines=16]
      types_or: [c, c++, objective-c]
