[project]
name = "spatialmp4"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
build-ffmpeg = "bash scripts/build_ffmpeg.sh"
build = "cmake -G Ninja -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -B build -S . && cmake --build build"
rebuild = "rm -rf build; cmake -B build -S . && cmake --build build"
test = "cd build && VIDEO=../video/test.mp4 ./test_reader"
test-python = "pytest -s python/tests"

[dependencies]
cmake = ">=3.24.1,<4.0"
ninja = ">=1.13.0,<2"
make = "*"
pkg-config = "*"
gcc = "*"
gxx = "*"
zlib = "*"
libpng = ">=1.6.43,<2"
libjpeg-turbo = "*"
freetype = "*"
harfbuzz = "*"
libuuid = "*"
libdrm = "*"
libxcb = "*"
libva = "*"
libass = "*"
fontconfig = "*"
expat = "*"
glib = "*"
pcre = "*"
graphite2 = "*"
fribidi = "*"
brotli = "*"
alsa-lib = "*"
pytest = ">=8.4.1,<9"
setuptools = ">=80.9.0,<81"
jpeg = ">=9e,<10a"
libvorbis = ">=1.3.7,<2"
numpy = "<2.0"
